interface ProjectData {
  projectType: string;
  location: string;
  soilType: string;
  terrain: string;
  buildingHeight?: string;
  buildingArea?: string;
  proximityToWater?: string;
}

interface RecommendationData {
  foundation: {
    type: string;
    description: string;
    considerations: string[];
  };
  drainage: {
    type: string;
    description: string;
    considerations: string[];
  };
  slopeStability: {
    risk: 'low' | 'moderate' | 'high';
    description: string;
    recommendations: string[];
  };
  timestamp: string;
}

/**
 * Generate a CSV file that can be imported into AutoCAD
 * This is another alternative approach
 */
export const exportAsCSV = (projectData: ProjectData, recommendations: RecommendationData): void => {
  try {
    // Format project type with first letter capitalized
    const formatProjectType = (type: string): string => {
      if (type === 'retaining-wall') return 'Retaining Wall';
      return type.charAt(0).toUpperCase() + type.slice(1);
    };

    // Create CSV content
    // Format: X,Y,Z,TEXT
    let csvContent = 'X,Y,Z,TEXT\n';
    
    // Title
    csvContent += `10,290,0,"CIVIWISE DESIGN RECOMMENDATIONS"\n`;
    
    // Project Information
    csvContent += `10,280,0,"Project Type: ${formatProjectType(projectData.projectType)}"\n`;
    
    let yPos = 275;
    
    if (projectData.location) {
      csvContent += `10,${yPos},0,"Location: ${projectData.location}"\n`;
      yPos -= 5;
    }
    
    csvContent += `10,${yPos},0,"Soil Type: ${projectData.soilType.charAt(0).toUpperCase() + projectData.soilType.slice(1)}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Terrain: ${projectData.terrain.replace('-', ' ').charAt(0).toUpperCase() + projectData.terrain.replace('-', ' ').slice(1)}"\n`;
    yPos -= 5;
    
    if (projectData.buildingHeight) {
      csvContent += `10,${yPos},0,"Building Height: ${projectData.buildingHeight} m"\n`;
      yPos -= 5;
    }
    
    if (projectData.buildingArea) {
      csvContent += `10,${yPos},0,"Building Area: ${projectData.buildingArea} sq.m"\n`;
      yPos -= 5;
    }
    
    if (projectData.proximityToWater) {
      csvContent += `10,${yPos},0,"Proximity to Water: ${projectData.proximityToWater}"\n`;
      yPos -= 5;
    }
    
    yPos -= 10;
    
    // Foundation Recommendations
    csvContent += `10,${yPos},0,"FOUNDATION RECOMMENDATIONS"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Type: ${recommendations.foundation.type}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"${recommendations.foundation.description}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Key Considerations:"\n`;
    yPos -= 5;
    
    recommendations.foundation.considerations.forEach((consideration, index) => {
      csvContent += `15,${yPos},0,"${index + 1}. ${consideration}"\n`;
      yPos -= 5;
    });
    
    yPos -= 5;
    
    // Drainage Recommendations
    csvContent += `10,${yPos},0,"DRAINAGE RECOMMENDATIONS"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Type: ${recommendations.drainage.type}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"${recommendations.drainage.description}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Key Considerations:"\n`;
    yPos -= 5;
    
    recommendations.drainage.considerations.forEach((consideration, index) => {
      csvContent += `15,${yPos},0,"${index + 1}. ${consideration}"\n`;
      yPos -= 5;
    });
    
    yPos -= 5;
    
    // Slope Stability Assessment
    csvContent += `10,${yPos},0,"SLOPE STABILITY ASSESSMENT"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Risk Level: ${recommendations.slopeStability.risk.toUpperCase()}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"${recommendations.slopeStability.description}"\n`;
    yPos -= 5;
    
    csvContent += `10,${yPos},0,"Recommendations:"\n`;
    yPos -= 5;
    
    recommendations.slopeStability.recommendations.forEach((recommendation, index) => {
      csvContent += `15,${yPos},0,"${index + 1}. ${recommendation}"\n`;
      yPos -= 5;
    });
    
    // Footer
    csvContent += `10,10,0,"Generated by CiviWise - Smart Civil Engineering Platform for Sri Lanka"\n`;
    csvContent += `10,5,0,"Generated on: ${new Date(recommendations.timestamp).toLocaleString()}"\n`;
    
    // Create a blob and download
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'CiviWise-Design-Recommendations.csv';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up the URL object
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Error generating CSV file:', error);
    alert('Error generating CSV file. Please check the console for details.');
  }
};
