interface ProjectData {
  projectType: string;
  location: string;
  soilType: string;
  terrain: string;
  buildingHeight?: string;
  buildingArea?: string;
  proximityToWater?: string;
}

interface RecommendationData {
  foundation: {
    type: string;
    description: string;
    considerations: string[];
  };
  drainage: {
    type: string;
    description: string;
    considerations: string[];
  };
  slopeStability: {
    risk: 'low' | 'moderate' | 'high';
    description: string;
    recommendations: string[];
  };
  timestamp: string;
}

/**
 * Generate a simple DXF file for AutoCAD
 * This uses a basic template approach rather than a library
 */
export const generateSimpleDXF = (projectData: ProjectData, recommendations: RecommendationData): void => {
  try {
    // Format project type with first letter capitalized
    const formatProjectType = (type: string): string => {
      if (type === 'retaining-wall') return 'Retaining Wall';
      return type.charAt(0).toUpperCase() + type.slice(1);
    };

    // Create a basic DXF template
    const dxfContent = `0
SECTION
2
HEADER
9
$ACADVER
1
AC1021
9
$INSBASE
10
0.0
20
0.0
30
0.0
0
ENDSEC
0
SECTION
2
TABLES
0
TABLE
2
LTYPE
0
LTYPE
2
CONTINUOUS
70
0
3
Solid line
72
65
73
0
40
0.0
0
ENDTAB
0
TABLE
2
LAYER
0
LAYER
2
0
70
0
62
7
6
CONTINUOUS
0
LAYER
2
TEXT
70
0
62
7
6
CONTINUOUS
0
ENDTAB
0
ENDSEC
0
SECTION
2
ENTITIES
0
TEXT
8
TEXT
10
10.0
20
290.0
30
0.0
40
5.0
1
CIVIWISE DESIGN RECOMMENDATIONS
0
TEXT
8
TEXT
10
10.0
20
280.0
30
0.0
40
3.0
1
Project Type: ${formatProjectType(projectData.projectType)}
0
TEXT
8
TEXT
10
10.0
20
275.0
30
0.0
40
3.0
1
Soil Type: ${projectData.soilType.charAt(0).toUpperCase() + projectData.soilType.slice(1)}
0
TEXT
8
TEXT
10
10.0
20
270.0
30
0.0
40
3.0
1
Terrain: ${projectData.terrain.replace('-', ' ').charAt(0).toUpperCase() + projectData.terrain.replace('-', ' ').slice(1)}
0
TEXT
8
TEXT
10
10.0
20
260.0
30
0.0
40
4.0
1
FOUNDATION RECOMMENDATIONS
0
TEXT
8
TEXT
10
10.0
20
255.0
30
0.0
40
3.0
1
Type: ${recommendations.foundation.type}
0
TEXT
8
TEXT
10
10.0
20
250.0
30
0.0
40
3.0
1
${recommendations.foundation.description}
0
TEXT
8
TEXT
10
10.0
20
240.0
30
0.0
40
4.0
1
DRAINAGE RECOMMENDATIONS
0
TEXT
8
TEXT
10
10.0
20
235.0
30
0.0
40
3.0
1
Type: ${recommendations.drainage.type}
0
TEXT
8
TEXT
10
10.0
20
230.0
30
0.0
40
3.0
1
${recommendations.drainage.description}
0
TEXT
8
TEXT
10
10.0
20
220.0
30
0.0
40
4.0
1
SLOPE STABILITY ASSESSMENT
0
TEXT
8
TEXT
10
10.0
20
215.0
30
0.0
40
3.0
1
Risk Level: ${recommendations.slopeStability.risk.toUpperCase()}
0
TEXT
8
TEXT
10
10.0
20
210.0
30
0.0
40
3.0
1
${recommendations.slopeStability.description}
0
TEXT
8
TEXT
10
10.0
20
10.0
30
0.0
40
2.0
1
Generated by CiviWise - Smart Civil Engineering Platform for Sri Lanka
0
LINE
8
0
10
0.0
20
0.0
30
0.0
11
300.0
21
0.0
31
0.0
0
LINE
8
0
10
300.0
20
0.0
30
0.0
11
300.0
21
210.0
31
0.0
0
LINE
8
0
10
300.0
20
210.0
30
0.0
11
0.0
21
210.0
31
0.0
0
LINE
8
0
10
0.0
20
210.0
30
0.0
11
0.0
21
0.0
31
0.0
0
ENDSEC
0
SECTION
2
OBJECTS
0
DICTIONARY
0
ENDSEC
0
EOF`;

    // Create a blob and download
    const blob = new Blob([dxfContent], { type: 'application/dxf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'CiviWise-Design-Recommendations.dxf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up the URL object
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Error generating simple DXF file:', error);
    alert('Error generating DXF file. Please check the console for details.');
  }
};
