interface ProjectData {
  projectType: string;
  location: string;
  soilType: string;
  terrain: string;
  buildingHeight?: string;
  buildingArea?: string;
  proximityToWater?: string;
}

interface RecommendationData {
  foundation: {
    type: string;
    description: string;
    considerations: string[];
  };
  drainage: {
    type: string;
    description: string;
    considerations: string[];
  };
  slopeStability: {
    risk: 'low' | 'moderate' | 'high';
    description: string;
    recommendations: string[];
  };
  timestamp: string;
}

/**
 * Generate a text file with AutoCAD instructions
 * This is a fallback method if DXF generation fails
 */
export const exportAsText = (projectData: ProjectData, recommendations: RecommendationData): void => {
  try {
    // Format project type with first letter capitalized
    const formatProjectType = (type: string): string => {
      if (type === 'retaining-wall') return 'Retaining Wall';
      return type.charAt(0).toUpperCase() + type.slice(1);
    };

    // Create text content
    let textContent = `CIVIWISE DESIGN RECOMMENDATIONS\n`;
    textContent += `=================================\n\n`;
    
    textContent += `PROJECT INFORMATION\n`;
    textContent += `-----------------\n`;
    textContent += `Project Type: ${formatProjectType(projectData.projectType)}\n`;
    
    if (projectData.location) {
      textContent += `Location: ${projectData.location}\n`;
    }
    
    textContent += `Soil Type: ${projectData.soilType.charAt(0).toUpperCase() + projectData.soilType.slice(1)}\n`;
    textContent += `Terrain: ${projectData.terrain.replace('-', ' ').charAt(0).toUpperCase() + projectData.terrain.replace('-', ' ').slice(1)}\n`;
    
    if (projectData.buildingHeight) {
      textContent += `Building Height: ${projectData.buildingHeight} m\n`;
    }
    
    if (projectData.buildingArea) {
      textContent += `Building Area: ${projectData.buildingArea} sq.m\n`;
    }
    
    if (projectData.proximityToWater) {
      textContent += `Proximity to Water: ${projectData.proximityToWater}\n`;
    }
    
    textContent += `\nFOUNDATION RECOMMENDATIONS\n`;
    textContent += `-------------------------\n`;
    textContent += `Type: ${recommendations.foundation.type}\n`;
    textContent += `Description: ${recommendations.foundation.description}\n`;
    textContent += `Key Considerations:\n`;
    
    recommendations.foundation.considerations.forEach((consideration, index) => {
      textContent += `${index + 1}. ${consideration}\n`;
    });
    
    textContent += `\nDRAINAGE RECOMMENDATIONS\n`;
    textContent += `------------------------\n`;
    textContent += `Type: ${recommendations.drainage.type}\n`;
    textContent += `Description: ${recommendations.drainage.description}\n`;
    textContent += `Key Considerations:\n`;
    
    recommendations.drainage.considerations.forEach((consideration, index) => {
      textContent += `${index + 1}. ${consideration}\n`;
    });
    
    textContent += `\nSLOPE STABILITY ASSESSMENT\n`;
    textContent += `-------------------------\n`;
    textContent += `Risk Level: ${recommendations.slopeStability.risk.toUpperCase()}\n`;
    textContent += `Description: ${recommendations.slopeStability.description}\n`;
    textContent += `Recommendations:\n`;
    
    recommendations.slopeStability.recommendations.forEach((recommendation, index) => {
      textContent += `${index + 1}. ${recommendation}\n`;
    });
    
    textContent += `\n=================================\n`;
    textContent += `Generated by CiviWise - Smart Civil Engineering Platform for Sri Lanka\n`;
    textContent += `Generated on: ${new Date(recommendations.timestamp).toLocaleString()}\n`;
    
    textContent += `\n\nINSTRUCTIONS FOR AUTOCAD IMPORT\n`;
    textContent += `-----------------------------\n`;
    textContent += `1. Open AutoCAD\n`;
    textContent += `2. Create a new drawing\n`;
    textContent += `3. Use the MTEXT command to create a text box\n`;
    textContent += `4. Copy and paste the content of this file into the text box\n`;
    textContent += `5. Format as needed\n`;

    // Create a blob and download
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'CiviWise-Design-Recommendations.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up the URL object
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Error generating text file:', error);
    alert('Error generating text file. Please check the console for details.');
  }
};
